### ISSUE TITLE
How to use the presets?

### ISSUE THREAD

**Issue by MatthiasKauer** [jonathanfilip/vim-lucius#9]
Hi,
I installed your color schemes via vundle. colo lucius does work. Adding LuciusBlack afterwards in vimrc gives an error however. Could you maybe paste the relevant that I need to paste in order to activate the light version?

I currently have (not working, gives E492: not an editor command LuciusBlack):
```
if has("gui_running")
colorscheme lucius "couldn't figure out how to set light version
LuciusBlack 
else
    colorscheme elflord
endif
```

**Comment by jonathanfilip** [comment]
I pretty much have the same thing (though I use it in term and GUI):

colorscheme lucius
LuciusLight

Honestly I'm not really sure why you would be getting an error, since this is how everyone I know uses it. The only thing I can think of is make sure you have your Vundle settings (Plugin) before you set the color scheme. I'm guessing you already do, however, or the "colorscheme lucius" line wouldn't work either.

If it still doesn't work for you, you can try setting the variables that the commands set for you:

    let g:lucius_style = a:style
    let g:lucius_contrast = a:contrast
    let g:lucius_contrast_bg = a:contrast_bg

command! LuciusLight call SetLucius("light", "normal", "normal")
            \ | colorscheme lucius

command! LuciusBlack call SetLucius("dark", "normal", "high")
            \ | colorscheme lucius

So for light:

let g:lucius_style = "light"
let g:lucius_contrast = "normal"
let g:lucius_contrast_bg = "normal"
coloscheme lucius

**Comment by MatthiasKauer** [comment]
ok, I figured it out; your black scheme is included in https://github.com/rodnaph/vim-color-schemes which I had also installed. This version doesn't include your other settings. to be fair I didn't really investigate that. After deactivating that Plugin in vundle, your scheme works as expected however.
Sorry for creating trouble.
